# Framework constants
DEFAULT_DQX_CONFIG_FILE = "idea4/configs/idea4_dqx_config.yaml"
RULE_ID_KEY = "id"
TABLE_KEY = "table"
TABLES_KEY="tables"
NAME_KEY="name"
FORMAT_KEY = "format"
SCHEMA_FILE_KEY = "schema_file"
TABLE_DELTA_KEY = "delta"
TABLE_MODE_KEY = "mode"
TABLE_DELTA_MODE_APPEND = "append"
TABLE_DELTA_MODE_OVERWRITE_BY_KEY = "overwrite"
OPTIONS_KEY = "options"
PARTITION_BY_KEY = "partitioned_by"
ENABLED_KEY = "enabled"
REFERENCE_TABLES_KEY = "reference_tables"

# Idea4 dqx constants
VERSION_KEY = "version"
VERSION_DESCRIPTION_KEY = "description"
GLOBAL_CONFIG_FILE_KEY = "global_config_file"
RULE_MAPPING_FILES_KEY = "rule_mapping_files"

# Sources YAML constants
SOURCES_KEY = "sources"
SOURCE_ID_KEY = "source_id"
RULE_PACK_ID_KEY = "validation_id"
TABLE_NAME_KEY = "table_name"
SUBQUERY_KEY = "subquery"
SQL_FILE_KEY = "sql_file"
SQL_FILE_TEXT_KEY = "_sql_file"
READ_TYPE_KEY = "read_type"
STREAM_KEY = "stream"
CDF_KEY = "cdf"

#  Rule Packs YAML constants
FAST_FAIL_KEY = "fast_fail"
RULE_PACKS_KEY = "rule_packs"
FAST_FAIL_RULE_CHAIN_KEY = "fast_fail_rule_chain"
RULE_VERSION_KEY = "rule_version"
EXTENDS_KEY = "extends"
IMPORTS_KEY = "imports"
KWARGS_KEY = "kwargs"
REPLACE_RULES_KEY = "replace_rules"
OVERRIDE_KEY = "override"
ID_KEY = "id"
COLUMNS_KEY = "columns"
RULES_KEY = "rules"
DIMENSION_KEY = "dimension"
CRITICALITY_KEY = "criticality"
MESSAGE_KEY = "message"
ARGUMENTS_KEY = "arguments"
CATEGORY_KEY = "category"
SUBCATEGORY_KEY = "subcategory"
RULE_TYPE_KEY = "rule_type"
TABLE_NAME_KEY = "table_name"
FILTER_KEY = "filter"
METADATA_KEY = "metadata"
VALIDATION_MESSAGE_KEY = "validation_message"

# Rule Mappings
ROW_RULES_KEY = "row_rules"
CALLABLE_REF_KEY = "callable_ref"
DESCRIPTION_KEY = "description"
SINCE_VERSION_KEY = "since_version"
DEPRECATED_KEY = "deprecated"
DATASET_RULES_KEY = "dataset_rules"

# DQX Persistence metrics
SUCCESS_KEY = "Success"
FAILURE_KEY = "Failure"
DQX_METRICS_PERSISTENCE_KEY = "dqx_metrics_persistence"
DQX_SUMMARY_TABLE_KEY = "dqx_summary"
DQX_QUARANTINE_TABLE_KEY = "dqx_quarantine"
SUMMARY_TABLE_KEY = "dqx_summary"
QUARANTINE_TABLE_KEY = "dqx_quarantine"

DQX_RUN_ID_KEY = "dqx_run_id"
DQX_RUN_TS_KEY = "dqx_run_ts"
DQX_VALIDATION_ID_KEY = "dqx_validation_id"
WORKSPACE_ID_KEY = "workspace_id"
NOTEBOOK_PATH_KEY = "notebook_path"
NOTEBOOK_ID_KEY = "notebook_id"
JOB_ID_KEY = "job_id"
RUN_ID_KEY = "run_id"
PARENT_RUN_ID_KEY = "parent_run_id"
TASK_RUN_ID_KEY = "task_run_id"
JOB_NAME_KEY = "job_name"
TASK_KEY_KEY = "task_key"

CLUSTER_ID_KEY = "cluster_id"
CLUSTER_NAME_KEY = "cluster_name"
USER_KEY = "user"
ORG_ID_KEY = "org_id"
TAGS_KEY = "tags"
RUNTIME_METADATA_KEY = "runtime_metadata"
